;;;;;;;;;;;;;;;;;;;;;; RV64

(rule
 (deps fack_rv64_startup.s)
 (targets fack_rv64_startup.o)
 (mode
  (promote (until-clean)))
 (action
  (run riscv64-linux-gnu-as -g -o %{targets} %{deps})))

(rule
 (deps fack_rv64.s)
 (targets fack_rv64.o)
 (mode
  (promote (until-clean)))
 (action
  (run riscv64-linux-gnu-as -g -o %{targets} %{deps})))

(rule
 (deps fack_rv64_startup.o fack_rv64.o)
 (targets fack_rv64.exe)
 (mode
  (promote (until-clean)))
 (action
  (run
   riscv64-linux-gnu-gcc
   -o
   %{targets}
   -L%{read:../risc_ocaml_lib.txt}
   %{deps}
   -lasmrun
   -lm)))

(cram
 (applies_to rv64)
 (deps fack_rv64.exe))
