(include dune.dump)

(rule
 (deps mini_gas_startup.s)
 (targets mini_gas_startup.o)
 (mode
  (promote (until-clean)))
 (action
  (run as -o %{targets} %{deps})))

(rule
 (deps mini_gas.s)
 (targets mini_gas.o)
 (mode
  (promote (until-clean)))
 (action
  (run as -o %{targets} %{deps})))

(rule
 (deps mini_gas_startup.o mini_gas.o)
 (targets mini_gas.exe)
 (action
  (run gcc -o %{targets} %{deps} -L%{ocaml_where} -lasmrun -lm)))

(cram
 (deps mini_gas.exe))

(rule
 (deps fac_gas_startup.s)
 (targets fac_gas_startup.o)
 (mode
  (promote (until-clean)))
 (action
  (run as -o %{targets} %{deps})))

(rule
 (deps fac_gas.s)
 (targets fac_gas.o)
 (mode
  (promote (until-clean)))
 (action
  (run as -o %{targets} %{deps})))

(rule
 (deps fac_gas_startup.o fac_gas.o)
 (targets fac_gas.exe)
 (mode
  (promote (until-clean)))
 (action
  (run gcc -o %{targets} %{deps} -L%{ocaml_where} -lasmrun -lm)))

(cram
 (deps fac_gas.exe))

;;;;;;;;;;;;;;;;;;;;;;

(rule
 (deps mini_nasm_startup.s)
 (targets mini_nasm_startup.o)
 (mode
  (promote (until-clean)))
 (action
  (run nasm -g -F dwarf -f elf64 -o %{targets} %{deps})))

(rule
 (deps mini_nasm.s)
 (targets mini_nasm.o)
 (mode
  (promote (until-clean)))
 (action
  (run nasm -g -F dwarf -f elf64 -o %{targets} %{deps})))

(rule
 (deps mini_nasm_startup.o mini_nasm.o)
 (targets mini_nasm.exe)
 (mode
  (promote (until-clean)))
 (action
  (run gcc -o %{targets} %{deps} -L%{ocaml_where} -lasmrun -lm)))

(cram
 (deps mini_nasm.exe))
