(env
 (dev
  (flags
   (:standard -warn-error -27-32-37))))

(library
 (name lib)
 (libraries angstrom)
 (modules lib)
 (wrapped false)
 (preprocess
  (pps ppx_deriving.show)))

(executable
 (name gas2nasm)
 (modules gas2nasm)
 (libraries angstrom lib)
 (preprocess
  (pps ppx_deriving.show)))

(library
 (name tests1)
 (modules tests1)
 (libraries lib)
 ;  (inline_tests)
 (preprocess
  (pps ppx_inline_test_nobase ppx_expect_nobase)))

(cram
 (applies_to tuple1)
 (deps tests/Tuple1_yasm.exe tests/Tuple1.exe))

(cram
 (applies_to Facacc)
 (deps tests/Facacc_yasm.exe tests/Facacc.exe))

(cram
 (applies_to Fack)
 (deps tests/Fack_yasm.exe tests/Fack.exe))

(cram
 (applies_to Fibk)
 (deps tests/Fibk_yasm.exe tests/Fibk.exe))
