# generated by OCaml 5.4
	.option pic

	.section .data
	.globl	camlFac.data_begin
	.type	camlFac.data_begin, @object
camlFac.data_begin:

	.text
	.globl	camlFac.code_begin
	.type	camlFac.code_begin, @object
camlFac.code_begin:

	.section .data
	.quad	3063
camlFac.5:
	.quad	camlFac.string_of_int_9
	.quad	0x100000000000005

	.section .data
	.quad	4087
camlFac.4:
	.quad	caml_curry2
	.quad	144115188075855879
	.quad	camlFac.output_string_15

	.section .data
	.quad	3063
camlFac.3:
	.quad	camlFac.print_endline_19
	.quad	0x100000000000005

	.section .data
	.quad	3063
camlFac.2:
	.quad	camlFac.fac_25
	.quad	72057594037927941

	.section .data
	.quad	5888
	.globl	camlFac
	.type	camlFac, @object
camlFac:
	.quad	1
	.quad	1
	.quad	1
	.quad	1
	.quad	1

	.section .data
	.globl	camlFac.gc_roots
	.type	camlFac.gc_roots, @object
camlFac.gc_roots:
	.quad	camlFac
	.quad	0
	.globl	camlFac.string_of_int_9
	.type	camlFac.string_of_int_9, @function

	.text
	.align	2
camlFac.string_of_int_9:
	addi	sp, sp, -8
	sd	ra, 0(sp)
.L100:
	mv	a1, a0
	la	a0, camlFac.1
	la	t2, caml_format_int
	call	caml_c_call@plt
.L101:
	ld	ra, 0(sp)
	addi	sp, sp, 8
	ret
	.size	camlFac.string_of_int_9, . - camlFac.string_of_int_9

#(function{fac.ml:14,18-72} camlFac.output_string_14 (oc/16: val s/17: val)
# (extcall "caml_ml_output"{fac.ml:15,2-47} oc/16 s/17 1
#  (+
#    (<<
#	  (let tmp/50 (- (<< (>>u (load int (+a s/17 -8)) 10) 3) 1)
#	     (- tmp/50 (load_mut unsigned int8 (+a s/17 tmp/50))))
#	  1)
#	1)
#  int,int,int,int->val))

	.globl	camlFac.output_string_15
	.type	camlFac.output_string_15, @function
	.text
	.align	2
camlFac.output_string_15:
	addi	sp, sp, -8
	sd	ra, 0(sp)
.L102:
	ld	a2, -8(a1)          # load int (+a s/17 -8)
	srli	a3, a2, 10      # remove color(2) + tag(8)
	slli	a4, a3, 3
	addi	a5, a4, -1      # a5=tmp50
	add	a6, a1, a5
	lbu	a7, 0(a6)
	sub	s2, a5, a7 # s2 = (- tmp/50 (load_mut unsigned int8 (+a s/17 tmp/50)))
	slli	s3, s2, 1
	addi	a3, s3, 1
	li	a2, 1
	la	t2, caml_ml_output
	call	caml_c_call@plt
.L103:
	ld	ra, 0(sp)
	addi	sp, sp, 8
	ret
	.size	camlFac.output_string_15, . - camlFac.output_string_15

	.globl	camlFac.print_endline_19
	.type	camlFac.print_endline_19, @function
	.text
	.align	2
camlFac.print_endline_19:
	ld	t1, 40(s11)
	addi	t1, t1, 320
	bltu	sp, t1, .L105
.L106:
	addi	sp, sp, -8
	sd	ra, 0(sp)
.L104:
	mv	a1, a0
	la	a2, camlFac
	ld	a0, 0(a2)
	call	camlFac.output_string_15@plt
.L107:
	li	a1, 21
	la	a4, camlFac
	ld	a0, 0(a4)
	la	t2, caml_ml_output_char
	call	caml_c_call@plt
.L108:
	la	a6, camlFac
	ld	a0, 0(a6)
	la	t2, caml_ml_flush
	call	caml_c_call@plt
.L109:
	ld	ra, 0(sp)
	addi	sp, sp, 8
	ret
.L105:
	li	t1, 33
	addi	sp, sp, -16
	sd	t1, 0(sp)
	sd	ra, 8(sp)
	call	caml_call_realloc_stack@plt
	ld	ra, 8(sp)
	addi	sp, sp, 16
	j	.L106
	.size	camlFac.print_endline_19, . - camlFac.print_endline_19

# (function{fac.ml:24,12-48} camlFac.fac_25 (n/26: int)
#  (if (< n/26 5) 3
#   (+
#    (* (+ n/26 -1)
#     (>>s (app{fac.ml:24,39-48} "camlFac.fac_25" (+ n/26 -2) val) 1))
#    1)))
	.globl	camlFac.fac_25
	.type	camlFac.fac_25, @function
	.text
	.align	2
camlFac.fac_25:
	ld	t1, 40(s11)   # s11 -- domain pointer
	addi	t1, t1, 328
	bltu	sp, t1, .L112
.L113:
	addi	sp, sp, -16
	sd	ra, 8(sp)
.L111:
	li	a1, 5
	bge	a0, a1, .L110
	li	a0, 3
	ld	ra, 8(sp)
	addi	sp, sp, 16
	ret
.L110:
	sd	a0, 0(sp)
	addi	a0, a0, -2
	call	camlFac.fac_25@plt
.L114:
	srai	a4, a0, 1
	ld	s3, 0(sp)
	addi	a5, s3, -1
	mul	a6, a5, a4
	addi	a0, a6, 1
	ld	ra, 8(sp)
	addi	sp, sp, 16
	ret
.L112:
	li	t1, 34
	addi	sp, sp, -16
	sd	t1, 0(sp)
	sd	ra, 8(sp)
	call	caml_call_realloc_stack@plt
	ld	ra, 8(sp)
	addi	sp, sp, 16
	j	.L113
	.size	camlFac.fac_25, . - camlFac.fac_25

	.section .data
	.quad	2044
camlFac.1:
	.byte	37,100
	.space	5
	.byte	5

# (data int 2044 "camlFac.1": string "%d" skip 5 byte 5)
# (function camlFac.entry ()
#  (let string_of_int/8 "camlFac.5"
#    (extcall "caml_initialize" "camlFac" string_of_int/8 ->unit))
#  (let output_string/14 "camlFac.4"
#    (extcall "caml_initialize" (+a "camlFac" 8) output_string/14 ->unit))
#  (let print_endline/18 "camlFac.3"
#    (extcall "caml_initialize" (+a "camlFac" 16) print_endline/18 ->unit))
#  (let clos/49 "camlFac.2"
#    (extcall "caml_initialize" (+a "camlFac" 24) clos/49 ->unit))
#  (let
#    *match*/44
#      (let
#        (stdout/27
#           (extcall "caml_ml_open_descriptor_out"{fac.ml:27,15-36} 3 int->val)
#         s/28
#           (app{fac.ml:28,10-31} "camlFac.string_of_int_8"
#             (app{fac.ml:28,24-31} "camlFac.fac_25" 11 val) val))
#        (app{fac.ml:29,2-24} "camlFac.print_endline_18" stdout/27 s/28 val))
#    [])
#  1)

	.globl	camlFac.entry
	.type	camlFac.entry, @function
	.text
	.align	2
camlFac.entry:
	ld	t1, 40(s11)
	addi	t1, t1, 320
	bltu	sp, t1, .L116
.L117:
	addi	sp, sp, -8
	sd	ra, 0(sp)
.L115:
	li	a0, 3
	la	t2, caml_ml_open_descriptor_out
	call	caml_c_call@plt
.L118:
	mv	a1, a0
	la	a0, camlFac
	mv	s0, sp
	ld	sp, 64(s11)
	call	caml_initialize@plt
	mv	sp, s0
	la	a1, camlFac.5
	la	a4, camlFac
	addi	a0, a4, 8
	mv	s0, sp
	ld	sp, 64(s11)
	call	caml_initialize@plt
	mv	sp, s0
	la	a1, camlFac.4
	la	a7, camlFac
	addi	a0, a7, 16
	mv	s0, sp
	ld	sp, 64(s11)
	call	caml_initialize@plt
	mv	sp, s0
	la	a1, camlFac.3
	la	s4, camlFac
	addi	a0, s4, 24
	mv	s0, sp
	ld	sp, 64(s11)
	call	caml_initialize@plt
	mv	sp, s0
	la	a1, camlFac.2
	la	s7, camlFac
	addi	a0, s7, 32
	mv	s0, sp
	ld	sp, 64(s11)
	call	caml_initialize@plt
	mv	sp, s0
	li	a0, 11
	call	camlFac.fac_25@plt
.L119:
	call	camlFac.string_of_int_9@plt
.L120:
	call	camlFac.print_endline_19@plt
.L121:
	li	a0, 1
	ld	ra, 0(sp)
	addi	sp, sp, 8
	ret
.L116:
	li	t1, 33
	addi	sp, sp, -16
	sd	t1, 0(sp)
	sd	ra, 8(sp)
	call	caml_call_realloc_stack@plt
	ld	ra, 8(sp)
	addi	sp, sp, 16
	j	.L117
	.size	camlFac.entry, . - camlFac.entry

.section .data
	.quad	caml_ml_output
	.quad	caml_ml_output_char
	.quad	caml_format_int
	.quad	caml_ml_flush
	.quad	caml_ml_open_descriptor_out
	.text
	.globl	camlFac.code_end
	.type	camlFac.code_end, @object
camlFac.code_end:
	.long	0

.section .data
	.globl	camlFac.data_end
	.type	camlFac.data_end, @object
	.quad	0
camlFac.data_end:
	.quad	0
.section .data
	.globl	camlFac.frametable
	.type	camlFac.frametable, @object
camlFac.frametable:
	.quad	10
	.quad	.L121
	.short	9
	.short	0
	.align	2
	.long	(.L122 - .) + 0x0
	.align	3
	.quad	.L120
	.short	9
	.short	0
	.align	2
	.long	(.L123 - .) + 0x0
	.align	3
	.quad	.L119
	.short	9
	.short	0
	.align	2
	.long	(.L124 - .) + 0x0
	.align	3
	.quad	.L118
	.short	9
	.short	0
	.align	2
	.long	(.L125 - .) + 0x0
	.align	3
	.quad	.L114
	.short	17
	.short	0
	.align	2
	.long	(.L126 - .) + 0x0
	.align	3
	.quad	.L109
	.short	9
	.short	0
	.align	2
	.long	(.L127 - .) + 0x0
	.align	3
	.quad	.L108
	.short	9
	.short	0
	.align	2
	.long	(.L128 - .) + 0x0
	.align	3
	.quad	.L107
	.short	9
	.short	0
	.align	2
	.long	(.L129 - .) + 0x0
	.align	3
	.quad	.L103
	.short	9
	.short	0
	.align	2
	.long	(.L130 - .) + 0x0
	.align	3
	.quad	.L101
	.short	9
	.short	0
	.align	2
	.long	(.L131 - .) + 0x0
	.align	3
	.align	2
.L129:
	.long	(.L133 - .) + 0x0
	.long	0x9008c0
	.align	2
.L124:
	.long	(.L134 - .) + 0x0
	.long	0xd09968
	.align	2
.L125:
	.long	(.L135 - .) + 0x0
	.long	0x203510
	.align	2
.L130:
	.long	(.L136 - .) + 0x0
	.long	0x780978
	.align	2
.L122:
	.long	(.L134 - .) + 0x0
	.long	0xd02570
	.align	2
.L128:
	.long	(.L133 - .) + 0x0
	.long	0x906988
	.align	2
.L127:
	.long	(.L133 - .) + 0x0
	.long	0x90cdf8
	.align	2
.L126:
	.long	(.L137 - .) + 0x0
	.long	0xc09d80
	.align	2
.L123:
	.long	(.L134 - .) + 0x0
	.long	0xd05d70
	.align	2
.L131:
	.long	(.L138 - .) + 0x0
	.long	0x405938
.L132:
	.byte	102,97,99,46,109,108,0
	.align	2
.L135:
	.long	(.L132 - .) + 0x0
	.byte	70,97,99,46,115,116,100,111,117,116,0
	.align	2
.L138:
	.long	(.L132 - .) + 0x0
	.asciz "Fac.string_of_int"
	.align	2
.L137:
	.long	(.L132 - .) + 0x0
	# .byte	70,97,99,46,102,97,99,0
	.asciz "Fac.fac"
	.align	2
.L133:
	.long	(.L132 - .) + 0x0
	.asciz "Fac.print_endline"
	# .byte	70,97,99,46,112,114,105,110,116,95,101,110,100,108,105,110
	# .byte	101,0
	.align	2
.L136:
	.long	(.L132 - .)
	.asciz	"Fac.output_string"
	# .byte	70,97,99,46,111,117,116,112,117,116,95,115,116,114,105,110
	# .byte	103,0
	.align	2
.L134:
	.long	(.L132 - .)
	.asciz	"Fac"
	# .byte	70,97,99,0
	.align	3
	.size	camlFac.frametable, . - camlFac.frametable
	.section .note.GNU-stack,"",%progbits
