(rule
 (deps MAIN_gas_startup.s)
 (targets MAIN_gas_startup.o)
 (mode
  (promote (until-clean)))
 (action
  (run as -o %{targets} %{deps})))

(rule
 (deps MAIN_gas.s)
 (targets MAIN_gas.o)
 (mode
  (promote (until-clean)))
 (action
  (run as -o %{targets} %{deps})))

(rule
 (deps MAIN_gas_startup.o MAIN_gas.o)
 (targets MAIN_gas.exe)
 (action
  (run gcc -o %{targets} %{deps} -L%{ocaml_where} -lasmrun -lm)))

(cram
 (deps MAIN_gas.exe))

;;;;

(rule
 (deps MAIN_nasm_startup.s)
 (targets MAIN_nasm_startup.o)
 (mode
  (promote (until-clean)))
 (action
  (run nasm -g -F dwarf -f elf64 -o %{targets} %{deps})))

(rule
 (deps MAIN_nasm.s)
 (targets MAIN_nasm.o)
 (mode
  (promote (until-clean)))
 (action
  (run nasm -g -F dwarf -f elf64 -o %{targets} %{deps})))

(rule
 (deps MAIN_nasm_startup.o MAIN_nasm.o)
 (targets MAIN_nasm.exe)
 (action
  (run gcc -o %{targets} %{deps} -L%{ocaml_where} -lasmrun -lm)))

(cram
 (deps MAIN_nasm.exe))
