(rule
 (deps tuple1.ml)
 (targets tuple1.s tuple1.o tuple1.exe.startup.s tuple1.exe)
 (mode
  (promote (until-clean)))
 (action
  (progn
   (run
    ocamlopt
    -dstartup
    -S
    %{deps}
    -nopervasives
    -verbose
    -o
    tuple1.exe
    -ccopt
    -lasmrun
    -ccopt
    -lm)
   ;   (run ls)
   )))

(rule
 (deps tuple1.exe.startup.s)
 (targets tuple1.startup.nasm.s)
 (mode
  (promote (until-clean)))
 (action
  (run ../gas2nasm.exe -startup -main Tuple1 %{deps} -o %{targets})))

(rule
 (deps tuple1.s)
 (targets tuple1.nasm.s)
 (mode
  (promote (until-clean)))
 (action
  (run ../gas2nasm.exe %{deps} -o %{targets})))

(rule
 (deps tuple1.startup.nasm.s)
 (targets tuple1_nasm_startup.o)
 ; (mode
 ;  (promote (until-clean)))
 (action
  (run nasm -g -F dwarf -f elf64 -o %{targets} %{deps})))

(rule
 (deps tuple1.nasm.s)
 (targets tuple1.nasm.o)
 (mode
  (promote (until-clean)))
 (action
  (run nasm -g -F dwarf -f elf64 -o %{targets} %{deps})))

(rule
 (deps tuple1_nasm_startup.o tuple1.nasm.o)
 (targets tuple1_nasm.exe)
 (mode
  (promote (until-clean)))
 (action
  (run gcc -o %{targets} %{deps} -L%{ocaml_where} -lasmrun -lm)))

(cram
 (deps tuple1_nasm.exe))
